version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    restart: always
    ports: 
      - "8000:80"
    depends_on: 
      - web
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
  web:
    build: .
    restart: always
    command: bash -c "python3 manage.py collectstatic --no-input && gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000" 
    depends_on:
      - db
    volumes:
      - ./static:/code/static
    env_file:
      - ./.env